/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2018-02-17 16:05:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import org.apache.commons.lang3.StringEscapeUtils;
import org.bonitasoft.console.common.server.jsp.JSPUtils;
import org.bonitasoft.console.common.server.jsp.JSPI18n;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    JSPUtils JSP = new JSPUtils(request, session);
    JSPI18n i18n = new JSPI18n(JSP); 

    // Build Action URL
    final String tenantId = StringEscapeUtils.escapeHtml4(JSP.getParameter("tenant"));
    String redirectUrl = JSP.getParameter("redirectUrl");

    StringBuffer actionUrl = new StringBuffer("loginservice?");
    StringBuffer styleUrl = new StringBuffer("portal/themeResource?theme=portal");
    if (tenantId != null) {
        actionUrl.append("tenant=").append(tenantId).append("&");
		styleUrl.append("&tenant=").append(tenantId);
    }
    
    if (redirectUrl != null) {
    	if (tenantId != null) {
    		redirectUrl = redirectUrl.replaceAll("[\\?&]tenant=\\d+$", "").replaceAll("tenant=\\d+&", "");
    		if (redirectUrl.contains("?")) {
    			redirectUrl += "&";
    		} else {
    			redirectUrl += "?";
    		}
    		redirectUrl += "tenant=" + tenantId;
    	}
        actionUrl.append("redirectUrl=" + URLEncoder.encode(redirectUrl, "UTF-8"));
    }

    // Error messages
    String errorMessage = "";
    boolean disableLogin = false;
    String noBonitaHomeMessage = request.getAttribute("noBonitaHomeMessage") + "";
	String noBonitaClientFileMessage = request.getAttribute("noBonitaClientFileMessage") + "";
	String loginFailMessage = request.getAttribute("loginFailMessage") + "";
	String tenantInMaintenanceMessage = request.getAttribute("tenantInMaintenanceMessage") + "";

    // Technical problems
    if (
        !JSP.getParameter("isPlatformCreated", true) ||
		!JSP.getParameter("isTenantCreated", true) ||
		"tenantNotActivated".equals(loginFailMessage) ||
		"noBonitaHomeMessage".equals(noBonitaHomeMessage) ||
		"noBonitaClientFileMessage".equals(noBonitaClientFileMessage)
	) {
        errorMessage = i18n._("The server is not available") + "<br />" + i18n._("Please, contact your administrator.");
        disableLogin = true;
    }
    // No profile for this user
    else if ("noProfileForUser".equals(loginFailMessage)) {
        errorMessage = i18n._("Login failed. No profile has been set up for this user. Contact your administrator.");
    }
 	// Tenant in Maintenance error
    else if ("tenantInMaintenanceMessage".equals(tenantInMaintenanceMessage)) {
        errorMessage = i18n._("This service is offline for maintenance. Please try later.");
    }
 	// Login or password error
    else if ("loginFailMessage".equals(loginFailMessage)) {
        errorMessage = i18n._("Unable to log in. Please check your username and password.");
    }

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<title>Bonita BPM Portal</title>\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"images/favicon2.ico\" />\n");
      out.write("<!-- Load LESS CSS -->\n");
      out.write("<script type=\"text/javascript\" src=\"portal/scripts/includes/array.prototype.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( styleUrl );
      out.write("&location=bonita.css\"/>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"portal/scripts/jquery/jquery-1.6.4.js\"></script>\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\t\tif (window != window.top) {\n");
      out.write("\t\t\ttry {\n");
      out.write("\t\t\t\tif (window.frameElement.id == \"bonitaframe\") {\n");
      out.write("\t\t\t\t\t/* if the login jsp is displayed inside a \"bonitaframe\" iframe it probably means the session is invalid so refresh the whole page */\n");
      out.write("\t\t\t\t\twindow.parent.location.reload();\n");
      out.write("\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t} catch (e) {\n");
      out.write("\t\t\t\t/* nothing to do (bonita is probably displayed inside an iframe of a different domain app) */\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t/* Add url hash to form action url */\n");
      out.write("\t\tvar form = $('#LoginForm');\n");
      out.write("\t\tform.attr('action', form.attr('action') + window.location.hash);\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body id=\"LoginPage\">\n");
      out.write("\t<div id=\"LoginHeader\"><h1><span>");
      out.print( i18n._("Welcome to") );
      out.write("</span> ");
      out.print( i18n._("Bonita BPM Portal") );
      out.write("</h1></div>\n");
      out.write("\t<div id=\"floater\"></div>\n");
      out.write("\t<div id=\"LoginFormContainer\" >\n");
      out.write("\t\t<div id=\"logo\">\n");
      out.write("\t\t\t<img src=\"");
      out.print( styleUrl );
      out.write("&location=skin/images/login-logo.png\"/>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"body\">\n");
      out.write("\t\t\t<form id=\"LoginForm\" action=\"");
      out.print(actionUrl);
      out.write("\" method=\"post\">\n");
      out.write("\t\t\t\t<div class=\"header\">\n");
      out.write("\t\t\t\t\t<h2>");
      out.print(i18n._("Login form"));
      out.write("</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<p class=\"error\">");
      out.print(errorMessage.length() > 0 ? errorMessage  : "");
      out.write("</p>\n");
      out.write("\t\t\t\t<div class=\"formentries\">\n");
      out.write("\t\t\t\t\t<div class=\"formentry\" title=\"");
      out.print(i18n._("Enter your login (username)"));
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<div class=\"label\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"username\">");
      out.print(i18n._("User"));
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"input\">\n");
      out.write("\t\t\t\t\t\t\t<input title=\"");
      out.print(i18n._("Username"));
      out.write("\" id=\"username\" name=\"username\" value=\"");
      out.print( StringEscapeUtils.escapeHtml4(JSP.getSessionOrCookie("username", "")) );
      out.write("\" placeholder=\"");
      out.print(i18n._("User"));
      out.write("\" type=\"text\" tabindex=\"1\" maxlength=\"255\" ");
      out.print(disableLogin ? "disabled=\"disabled\" " : "");
      out.write(" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formentry\" title=\"");
      out.print(i18n._("Enter your password"));
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<div class=\"label\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\">");
      out.print(i18n._("Password"));
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"input\">\n");
      out.write("\t\t\t\t\t\t\t<input title=\"");
      out.print(i18n._("Password"));
      out.write("\" id=\"password\" name=\"password\" type=\"password\" tabindex=\"2\" maxlength=\"50\" placeholder=\"");
      out.print(i18n._("Password"));
      out.write('"');
      out.write(' ');
      out.print(disableLogin ? "disabled=\"disabled\" " : "");
      out.write(" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input name=\"_l\" type=\"hidden\" value=\"");
      out.print(i18n.getLocale());
      out.write("\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"formactions\">\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"");
      out.print(i18n._("Login"));
      out.write('"');
      out.write(' ');
      out.print(disableLogin ? "disabled=\"disabled\" " : "");
      out.write(" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
